using SpiceSharp.Attributes;
using SpiceSharp.Behaviors;
using SpiceSharp.Components;
using SpiceSharp.Components.NoiseSources;
using SpiceSharp.ParameterSets;
using SpiceSharp.Simulations;

namespace SpiceSharpTest.Simulations;

/// <summary>
/// Parameters for a <see cref="FlickerInjector"/>.
/// </summary>
[GeneratedParameters]
public partial class FlickerInjectorParameters : ParameterSet<FlickerInjectorParameters>
{
    /// <summary>
    /// Gets or sets the coefficient of the injected density, the <c>A</c> of <c>A/f^beta</c>.
    /// </summary>
    [ParameterName("coefficient"), ParameterInfo("The coefficient of the injected density")]
    public double Coefficient { get; set; }

    /// <summary>
    /// Gets or sets the roll-off exponent of the injected density.
    /// </summary>
    [ParameterName("beta"), ParameterInfo("The roll-off exponent of the injected density")]
    public double Exponent { get; set; } = 1.0;
}

/// <summary>
/// A two-terminal component that injects a <c>A/f^beta</c> noise current. It exists because no
/// device in the framework can supply a roll-off exponent other than 1 - there is no <c>ef</c> model
/// parameter anywhere - so the extension point is the only way to exercise the rest of the range.
/// </summary>
[Pin(0, "A"), Pin(1, "B"), AutoGeneratedBehaviors]
public partial class FlickerInjector : Component<FlickerInjectorParameters>
{
    /// <summary>
    /// The number of pins.
    /// </summary>
    public const int PinCount = 2;

    /// <summary>
    /// Initializes a new instance of the <see cref="FlickerInjector"/> class.
    /// </summary>
    /// <param name="name">The name of the component.</param>
    public FlickerInjector(string name)
        : base(name, PinCount)
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="FlickerInjector"/> class.
    /// </summary>
    /// <param name="name">The name of the component.</param>
    /// <param name="pos">The positive node.</param>
    /// <param name="neg">The negative node.</param>
    /// <param name="coefficient">The coefficient of the injected density.</param>
    /// <param name="exponent">The roll-off exponent of the injected density.</param>
    public FlickerInjector(string name, string pos, string neg, double coefficient, double exponent)
        : this(name)
    {
        Parameters.Coefficient = coefficient;
        Parameters.Exponent = exponent;
        Connect(pos, neg);
    }
}

/// <summary>
/// The transient noise behavior of a <see cref="FlickerInjector"/>.
/// </summary>
[BehaviorFor(typeof(FlickerInjector)), AddBehaviorIfNo(typeof(ITimeNoiseBehavior))]
public class FlickerInjectorBehavior : Behavior,
    ITimeNoiseBehavior,
    IParameterized<FlickerInjectorParameters>
{
    private readonly TimeNoiseFlicker _source;

    /// <inheritdoc/>
    public FlickerInjectorParameters Parameters { get; }

    /// <inheritdoc/>
    public double NoiseDensity => _source.NoiseDensity;

    /// <inheritdoc/>
    public double Current => _source.Current;

    /// <summary>
    /// Initializes a new instance of the <see cref="FlickerInjectorBehavior"/> class.
    /// </summary>
    /// <param name="context">The binding context.</param>
    public FlickerInjectorBehavior(IComponentBindingContext context)
        : base(context)
    {
        Parameters = context.GetParameterSet<FlickerInjectorParameters>();
        var biasing = context.GetState<IBiasingSimulationState>();
        var noise = context.GetState<ITimeNoiseSimulationState>();
        _source = new TimeNoiseFlicker(Name, noise, biasing,
            biasing.GetSharedVariable(context.Nodes[0]),
            biasing.GetSharedVariable(context.Nodes[1]),
            Parameters.Exponent);

        // The coefficient is a parameter rather than an operating point, so a unit current with a
        // unit exponent hands it over unchanged and it never has to be refreshed again.
        _source.Compute(Parameters.Coefficient, 1.0, 1.0);
    }

    /// <inheritdoc/>
    void ITimeNoiseBehavior.Probe() => _source.Probe();

    /// <inheritdoc/>
    void ITimeNoiseBehavior.Inject() => _source.Inject();
}
