using SpiceSharp.Attributes;
using SpiceSharp.Behaviors;
using SpiceSharp.Components;
using SpiceSharp.Components.NoiseSources;
using SpiceSharp.ParameterSets;
using SpiceSharp.Simulations;

namespace SpiceSharpTest.Simulations;

/// <summary>
/// Parameters for a <see cref="NoiseInjector"/>.
/// </summary>
[GeneratedParameters]
public partial class NoiseInjectorParameters : ParameterSet<NoiseInjectorParameters>
{
    /// <summary>
    /// Gets or sets the one-sided power spectral density of the injected noise current.
    /// </summary>
    [ParameterName("density"), ParameterInfo("The one-sided power spectral density", Units = "A^2/Hz")]
    public double NoiseDensity { get; set; }
}

/// <summary>
/// A two-terminal component that is nothing but a noise source of a user-specified power spectral
/// density. It exists to check that a device outside the framework can take part in a
/// <see cref="NoiseTransient"/> analysis through <see cref="ITimeNoiseBehavior"/> alone.
/// </summary>
[Pin(0, "A"), Pin(1, "B"), AutoGeneratedBehaviors]
public partial class NoiseInjector : Component<NoiseInjectorParameters>
{
    /// <summary>
    /// The number of pins.
    /// </summary>
    public const int PinCount = 2;

    /// <summary>
    /// Initializes a new instance of the <see cref="NoiseInjector"/> class.
    /// </summary>
    /// <param name="name">The name of the component.</param>
    public NoiseInjector(string name)
        : base(name, PinCount)
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="NoiseInjector"/> class.
    /// </summary>
    /// <param name="name">The name of the component.</param>
    /// <param name="pos">The positive node.</param>
    /// <param name="neg">The negative node.</param>
    /// <param name="density">The one-sided power spectral density, in A^2/Hz.</param>
    public NoiseInjector(string name, string pos, string neg, double density)
        : this(name)
    {
        Parameters.NoiseDensity = density;
        Connect(pos, neg);
    }
}

/// <summary>
/// The noise source of a <see cref="NoiseInjector"/>: a current whose one-sided power spectral
/// density is whatever the caller says it is.
/// </summary>
/// <remarks>
/// There is no such primitive in the framework, because every device in it follows either the
/// thermal or the shot law. This is what a device that follows neither has to write, and it is
/// deliberately the whole of it.
/// </remarks>
public class FlatNoiseSource : TimeNoiseCurrentSource
{
    /// <summary>
    /// Initializes a new instance of the <see cref="FlatNoiseSource"/> class.
    /// </summary>
    /// <param name="name">The name of the noise source.</param>
    /// <param name="noise">The transient noise simulation state.</param>
    /// <param name="biasing">The biasing simulation state.</param>
    /// <param name="pos">The positive node.</param>
    /// <param name="neg">The negative node.</param>
    public FlatNoiseSource(string name, ITimeNoiseSimulationState noise, IBiasingSimulationState biasing,
        IVariable<double> pos, IVariable<double> neg)
        : base(name, noise, biasing, pos, neg)
    {
    }

    /// <summary>
    /// Sets the one-sided power spectral density of the source.
    /// </summary>
    /// <param name="density">The density, in A^2/Hz.</param>
    public void Compute(double density) => SetNoiseDensity(density);
}

/// <summary>
/// The transient noise behavior of a <see cref="NoiseInjector"/>.
/// </summary>
[BehaviorFor(typeof(NoiseInjector)), AddBehaviorIfNo(typeof(ITimeNoiseBehavior))]
public class NoiseInjectorBehavior : Behavior,
    ITimeNoiseBehavior,
    IParameterized<NoiseInjectorParameters>
{
    private readonly FlatNoiseSource _source;

    /// <inheritdoc/>
    public NoiseInjectorParameters Parameters { get; }

    /// <inheritdoc/>
    public double NoiseDensity => _source.NoiseDensity;

    /// <inheritdoc/>
    public double Current => _source.Current;

    /// <summary>
    /// Initializes a new instance of the <see cref="NoiseInjectorBehavior"/> class.
    /// </summary>
    /// <param name="context">The binding context.</param>
    public NoiseInjectorBehavior(IComponentBindingContext context)
        : base(context)
    {
        Parameters = context.GetParameterSet<NoiseInjectorParameters>();
        var biasing = context.GetState<IBiasingSimulationState>();
        var noise = context.GetState<ITimeNoiseSimulationState>();
        _source = new FlatNoiseSource(Name, noise, biasing,
            biasing.GetSharedVariable(context.Nodes[0]),
            biasing.GetSharedVariable(context.Nodes[1]));

        // The density is a parameter rather than an operating point, so it never has to be
        // refreshed again.
        _source.Compute(Parameters.NoiseDensity);
    }

    /// <inheritdoc/>
    void ITimeNoiseBehavior.ProbeNoise() => _source.ProbeNoise();

    /// <inheritdoc/>
    void IBiasingBehavior.Load() => _source.InjectNoise();
}
