/* Generated By:CSharpCC: Do not edit this line. SpiceSharpExpressionParserConstants.cs */
namespace SpiceSharp.Parser.Expressions{
public  class SpiceSharpExpressionParserConstants {

  public const int EOF = 0;
  public const int ADD = 3;
  public const int MULTIPLY = 4;
  public const int SUBTRACT = 5;
  public const int DIVIDE = 6;
  public const int NOT = 7;
  public const int EQUALS = 8;
  public const int NOTEQUALS = 9;
  public const int GREATERTHAN = 10;
  public const int GREATERTHANEQUAL = 11;
  public const int SMALLERTHAN = 12;
  public const int SMALLERTHANEQUAL = 13;
  public const int AND = 14;
  public const int OR = 15;
  public const int COMMA = 16;
  public const int MODULO = 17;
  public const int QUESTION = 18;
  public const int COLON = 19;
  public const int RBLEFT = 20;
  public const int RBRIGHT = 21;
  public const int VALUE = 22;
  public const int SCIVALUE = 23;
  public const int SPICEVALUE = 24;
  public const int STRING = 25;
  public const int WORD = 26;
  public const int DIGIT = 27;
  public const int LETTER = 28;
  public const int CHARACTER = 29;

  public const int DEFAULT = 0;

  public readonly string[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"+\"",
    "\"*\"",
    "\"-\"",
    "\"/\"",
    "\"!\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"&&\"",
    "\"||\"",
    "\",\"",
    "\"%\"",
    "\"?\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "<VALUE>",
    "<SCIVALUE>",
    "<SPICEVALUE>",
    "<STRING>",
    "<WORD>",
    "<DIGIT>",
    "<LETTER>",
    "<CHARACTER>",
  };

}
}
