using SpiceSharp.Attributes;
using SpiceSharp.Components.Resistors;
using SpiceSharp.Entities;
using SpiceSharp.ParameterSets;
using System;

namespace SpiceSharp.Components
{
    /// <summary>
    /// A model for semiconductor <see cref="Resistor" />
    /// </summary>
    /// <seealso cref="Entity" />
    /// <seealso cref="IParameterized{T}" />
    /// <seealso cref="IParameterized{P}" />
    /// <seealso cref="ModelParameters" />
    [AutoGeneratedBehaviors]
    public partial class ResistorModel : Entity<ModelParameters>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResistorModel"/> class.
        /// </summary>
        /// <param name="name">The name of the model.</param>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="name"/> is <c>null</c>.</exception>
        public ResistorModel(string name)
            : base(name)
        {
        }
    }
}
