using System;

namespace SpiceSharp.Attributes
{
    /// <summary>
    /// An attribute that can be used to indicate that an entity has an auto-generated CreateBehaviors method.
    /// </summary>
    public class AutoGeneratedBehaviorsAttribute : Attribute
    {
    }
}
