using SpiceSharp.Attributes;
using SpiceSharp.Components.JFETs;
using SpiceSharp.Entities;
using SpiceSharp.ParameterSets;

namespace SpiceSharp.Components
{
    /// <summary>
    /// Model for a <see cref="JFET" />.
    /// </summary>
    /// <seealso cref="Entity"/>
    /// <seealso cref="BindingContext"/>
    /// <seealso cref="IParameterized{P}"/>
    /// <seealso cref="ModelParameters"/>
    [AutoGeneratedBehaviors]
    public partial class JFETModel : Entity<ModelParameters>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JFETModel"/> class.
        /// </summary>
        /// <param name="name">The name of the model.</param>
        public JFETModel(string name)
            : base(name)
        {
        }
    }
}
