/* Generated By:CSharpCC: Do not edit this line. SpiceSharpParserTokenManager.cs */
namespace SpiceSharp.Parser {

using System;
using System.Collections.Generic;
using SpiceSharp;
using SpiceSharp.Parser.Readers;

public  class SpiceSharpParserTokenManager : SpiceSharpParserConstants {
  public  System.IO.TextWriter debugStream = Console.Out;
  public  void SetDebugStream(System.IO.TextWriter ds) { debugStream = ds; }
private int mccStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private int mccStartNfa_0(int pos, long active0)
{
   return mccMoveNfa_0(mccStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int mccStopAtPos(int pos, int kind)
{
   mccmatchedKind = kind;
   mccmatchedPos = pos;
   return pos + 1;
}
private int mccStartNfaWithStates_0(int pos, int kind, int state) {
   mccmatchedKind = kind;
   mccmatchedPos = pos;
   try { curChar = input_stream.ReadChar(); }
   catch(System.IO.IOException) { return pos + 1; }
   return mccMoveNfa_0(state, pos + 1);
}
private int mccMoveStringLiteralDfa0_0()
{
   switch((int)curChar) {
      case 40:
         return mccStopAtPos(0, 1);
      case 41:
         return mccStopAtPos(0, 2);
      case 42:
         return mccStartNfaWithStates_0(0, 10, 34);
      case 43:
         return mccStartNfaWithStates_0(0, 9, 35);
      case 44:
         return mccStopAtPos(0, 12);
      case 46:
         return mccStartNfaWithStates_0(0, 11, 19);
      case 61:
         return mccStopAtPos(0, 3);
      case 91:
         return mccStopAtPos(0, 4);
      case 93:
         return mccStopAtPos(0, 5);
      default :
         return mccMoveNfa_0(0, 0);
   }
}
private void mccCheckNAdd(int state)
{
   if (mccrounds[state] != mccround)
   {
      mccstateSet[mccnewStateCnt++] = state;
      mccrounds[state] = mccround;
   }
}
private void mccAddStates(int start, int end)
{
   do {
      mccstateSet[mccnewStateCnt++] = mccnextStates[start];
   } while (start++ != end);
}
private void mccCheckNAddTwoStates(int state1, int state2)
{
   mccCheckNAdd(state1);
   mccCheckNAdd(state2);
}
private void mccCheckNAddStates(int start, int end)
{
   do {
      mccCheckNAdd(mccnextStates[start]);
   } while (start++ != end);
}
private void mccCheckNAddStates(int start)
{
   mccCheckNAdd(mccnextStates[start]);
   mccCheckNAdd(mccnextStates[start + 1]);
}
static readonly long[] mccbitVec0 = {
   0L, 0L, -1L, -1L
};
private int mccMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   mccnewStateCnt = 34;
   int i = 1;
   mccstateSet[0] = startState;
   int j, kind = Int32.MaxValue;
   for (;;)
   {
      if (++mccround == Int32.MaxValue)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(mccstateSet[--i])
            {
               case 34:
                  if ((-9217 & l) != 0L)
                     mccCheckNAddStates(0, 2);
                  else if ((9216 & l) != 0L)
                  {
                     if (kind > 8)
                        kind = 8;
                  }
                  if (curChar == 13)
                     mccstateSet[mccnewStateCnt++] = 3;
                  break;
               case 35:
                  if ((287948901175001088 & l) != 0L)
                  {
                     if (kind > 15)
                        kind = 15;
                     mccCheckNAddStates(3, 6);
                  }
                  else if (curChar == 46)
                     mccCheckNAdd(19);
                  break;
               case 0:
                  if ((287948901175001088 & l) != 0L)
                  {
                     if (kind > 19)
                        kind = 19;
                     mccCheckNAdd(33);
                  }
                  else if ((2305846307748577280 & l) != 0L)
                  {
                     if (kind > 13)
                        kind = 13;
                  }
                  else if ((43980465111040 & l) != 0L)
                     mccCheckNAddTwoStates(10, 18);
                  else if ((9216 & l) != 0L)
                  {
                     if (kind > 14)
                        kind = 14;
                  }
                  else if (curChar == 34)
                     mccCheckNAddStates(7, 9);
                  else if (curChar == 46)
                     mccCheckNAdd(19);
                  else if (curChar == 42)
                     mccCheckNAddStates(0, 2);
                  if ((287948901175001088 & l) != 0L)
                  {
                     if (kind > 15)
                        kind = 15;
                     mccCheckNAddStates(3, 6);
                  }
                  else if (curChar == 13)
                     mccstateSet[mccnewStateCnt++] = 7;
                  break;
               case 1:
                  if ((-9217 & l) != 0L)
                     mccCheckNAddStates(0, 2);
                  break;
               case 2:
                  if ((9216 & l) != 0L && kind > 8)
                     kind = 8;
                  break;
               case 3:
                  if (curChar == 10 && kind > 8)
                     kind = 8;
                  break;
               case 4:
                  if (curChar == 13)
                     mccstateSet[mccnewStateCnt++] = 3;
                  break;
               case 5:
                  if ((2305846307748577280 & l) != 0L && kind > 13)
                     kind = 13;
                  break;
               case 6:
                  if ((9216 & l) != 0L && kind > 14)
                     kind = 14;
                  break;
               case 7:
                  if (curChar == 10 && kind > 14)
                     kind = 14;
                  break;
               case 8:
                  if (curChar == 13)
                     mccstateSet[mccnewStateCnt++] = 7;
                  break;
               case 9:
                  if ((43980465111040 & l) != 0L)
                     mccCheckNAddTwoStates(10, 18);
                  break;
               case 10:
                  if ((287948901175001088 & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  mccCheckNAddStates(3, 6);
                  break;
               case 11:
                  if (curChar != 46)
                     break;
                  if (kind > 15)
                     kind = 15;
                  mccCheckNAddStates(10, 12);
                  break;
               case 12:
                  if ((287948901175001088 & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  mccCheckNAddStates(10, 12);
                  break;
               case 14:
                  if ((43980465111040 & l) != 0L)
                     mccCheckNAdd(15);
                  break;
               case 15:
                  if ((287948901175001088 & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  mccCheckNAdd(15);
                  break;
               case 18:
                  if (curChar == 46)
                     mccCheckNAdd(19);
                  break;
               case 19:
                  if ((287948901175001088 & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  mccCheckNAddStates(13, 15);
                  break;
               case 20:
                  if (curChar == 34)
                     mccCheckNAddStates(7, 9);
                  break;
               case 21:
                  if ((-17179878401 & l) != 0L)
                     mccCheckNAddStates(7, 9);
                  break;
               case 23:
                  if ((566935692288 & l) != 0L)
                     mccCheckNAddStates(7, 9);
                  break;
               case 24:
                  if (curChar == 34 && kind > 16)
                     kind = 16;
                  break;
               case 25:
                  if (curChar == 10)
                     mccCheckNAddStates(7, 9);
                  break;
               case 26:
                  if (curChar == 13)
                     mccstateSet[mccnewStateCnt++] = 25;
                  break;
               case 29:
                  if ((576285010831605760 & l) == 0L)
                     break;
                  if (kind > 17)
                     kind = 17;
                  mccstateSet[mccnewStateCnt++] = 29;
                  break;
               case 31:
                  if ((576285010831605760 & l) == 0L)
                     break;
                  if (kind > 18)
                     kind = 18;
                  mccstateSet[mccnewStateCnt++] = 31;
                  break;
               case 32:
                  if ((287948901175001088 & l) == 0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  mccCheckNAdd(33);
                  break;
               case 33:
                  if ((576285010831605760 & l) == 0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  mccCheckNAdd(33);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 63);
         do
         {
            switch(mccstateSet[--i])
            {
               case 34:
               case 1:
                  mccCheckNAddStates(0, 2);
                  break;
               case 0:
                  if ((576460745995190270 & l) != 0L)
                  {
                     if (kind > 19)
                        kind = 19;
                     mccCheckNAdd(33);
                  }
                  else if ((671088640 & l) != 0L)
                  {
                     if (kind > 13)
                        kind = 13;
                  }
                  else if (curChar == 64)
                     mccstateSet[mccnewStateCnt++] = 28;
                  if ((576460743847706622 & l) != 0L)
                  {
                     if (kind > 18)
                        kind = 18;
                     mccCheckNAdd(31);
                  }
                  break;
               case 5:
                  if ((671088640 & l) != 0L && kind > 13)
                     kind = 13;
                  break;
               case 13:
                  if ((137438953504 & l) != 0L)
                     mccAddStates(16, 17);
                  break;
               case 16:
                  if ((13907447705069760 & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  mccCheckNAdd(17);
                  break;
               case 17:
                  if ((576460743847706622 & l) == 0L)
                     break;
                  if (kind > 15)
                     kind = 15;
                  mccCheckNAdd(17);
                  break;
               case 21:
                  if ((-268435457 & l) != 0L)
                     mccCheckNAddStates(7, 9);
                  break;
               case 22:
                  if (curChar == 92)
                     mccAddStates(18, 19);
                  break;
               case 23:
                  if ((5700160605929540 & l) != 0L)
                     mccCheckNAddStates(7, 9);
                  break;
               case 27:
                  if (curChar == 64)
                     mccstateSet[mccnewStateCnt++] = 28;
                  break;
               case 28:
                  if ((576460743847706622 & l) == 0L)
                     break;
                  if (kind > 17)
                     kind = 17;
                  mccCheckNAdd(29);
                  break;
               case 29:
                  if ((576460745995190270 & l) == 0L)
                     break;
                  if (kind > 17)
                     kind = 17;
                  mccCheckNAdd(29);
                  break;
               case 30:
                  if ((576460743847706622 & l) == 0L)
                     break;
                  if (kind > 18)
                     kind = 18;
                  mccCheckNAdd(31);
                  break;
               case 31:
                  if ((576460745995190270 & l) == 0L)
                     break;
                  if (kind > 18)
                     kind = 18;
                  mccCheckNAdd(31);
                  break;
               case 32:
               case 33:
                  if ((576460745995190270 & l) == 0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  mccCheckNAdd(33);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 63);
         do
         {
            switch(mccstateSet[--i])
            {
               case 34:
               case 1:
                  if ((mccbitVec0[i2] & l2) != 0L)
                     mccCheckNAddStates(0, 2);
                  break;
               case 21:
                  if ((mccbitVec0[i2] & l2) != 0L)
                     mccAddStates(7, 9);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != Int32.MaxValue)
      {
         mccmatchedKind = kind;
         mccmatchedPos = curPos;
         kind = Int32.MaxValue;
      }
      ++curPos;
      if ((i = mccnewStateCnt) == (startsAt = 34 - (mccnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.ReadChar(); }
      catch(System.IO.IOException) { return curPos; }
   }
}
static readonly int[] mccnextStates = {
   1, 2, 4, 10, 11, 13, 16, 21, 22, 24, 12, 13, 16, 19, 13, 16, 
   14, 15, 23, 26, 
};
public static readonly string[] mccstrLiteralImages = {
"", "(", ")", "=", "[", "]", null, null, null, "+", "*", ".", ",", null, null, 
null, null, null, null, null, null, null, null, null, };
public static readonly string[] lexStateNames = {
   "DEFAULT", 
};
static readonly long[] mcctoToken = {
   1048127, 
};
static readonly long[] mcctoSkip = {
   448, 
};
protected SimpleCharStream input_stream;
private readonly int[] mccrounds = new int[34];
private readonly int[] mccstateSet = new int[68];
protected char curChar;
public SpiceSharpParserTokenManager(SimpleCharStream stream) {
   if (SimpleCharStream.staticFlag)
      throw new System.SystemException("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public SpiceSharpParserTokenManager(SimpleCharStream stream, int lexState)
   : this(stream) {
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream) {
   mccmatchedPos = mccnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   mccround = -2147483647;
   for (i = 34; i-- > 0;)
      mccrounds[i] = Int32.MinValue;
}
public void ReInit(SimpleCharStream stream, int lexState) {
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState) {
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.InvalidLexicalState);
   else
      curLexState = lexState;
}

protected Token mccFillToken()
{
   Token t = Token.NewToken(mccmatchedKind);
   t.kind = mccmatchedKind;
   string im = mccstrLiteralImages[mccmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.BeginLine;
   t.beginColumn = input_stream.BeginColumn;
   t.endLine = input_stream.EndLine;
   t.endColumn = input_stream.EndColumn;
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int mccnewStateCnt;
int mccround;
int mccmatchedPos;
int mccmatchedKind;

public Token GetNextToken() {
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

for (;;) {
   try {
      curChar = input_stream.BeginToken();
   } catch(System.IO.IOException) {
      mccmatchedKind = 0;
      matchedToken = mccFillToken();
      return matchedToken;
   }

   try { input_stream.Backup(0);
      while (curChar <= ' ' && (4294967808L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   } catch (System.IO.IOException) { goto EOFLoop; }
   mccmatchedKind = Int32.MaxValue;
   mccmatchedPos = 0;
   curPos = mccMoveStringLiteralDfa0_0();
   if (mccmatchedKind != Int32.MaxValue) {
      if (mccmatchedPos + 1 < curPos)
         input_stream.Backup(curPos - mccmatchedPos - 1);
      if ((mcctoToken[mccmatchedKind >> 6] & (1L << (mccmatchedKind & 63))) != 0L) {
         matchedToken = mccFillToken();
         return matchedToken;
      }
      else
      {
         goto EOFLoop;
      }
   }
   int error_line = input_stream.EndLine;
   int error_column = input_stream.EndColumn;
   string error_after = null;
   bool EOFSeen = false;
   try { input_stream.ReadChar(); input_stream.Backup(1); }
   catch (System.IO.IOException) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      } else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.Backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LexicalError);
EOFLoop: ;
  }
}

}
}
