/* Generated By:CSharpCC: Do not edit this line. SpiceSharpParserConstants.cs */
namespace SpiceSharp.Parser
{
    /// <summary>
    /// Collection of constants used for parsing
    /// This class is created by CSharpCC (a port of JavaCC to C#). Refer to spicelang.cc for the syntax.
    /// </summary>
    public class SpiceSharpParserConstants
    {

        public const int EOF = 0;
        public const int ASTERISK = 11;
        public const int MINUS = 12;
        public const int DOT = 13;
        public const int COMMA = 14;
        public const int DELIMITER = 15;
        public const int NEWLINE = 16;
        public const int ENDS = 17;
        public const int END = 18;
        public const int VALUE = 19;
        public const int STRING = 20;
        public const int EXPRESSION = 21;
        public const int REFERENCE = 22;
        public const int WORD = 23;
        public const int IDENTIFIER = 24;
        public const int DIGIT = 25;
        public const int LETTER = 26;
        public const int CHARACTER = 27;
        public const int SPECIAL = 28;

        public const int DEFAULT = 0;

        public readonly string[] tokenImage = {
            "<EOF>",
            "\"SUBCKT\"",
            "\"MODEL\"",
            "\"(\"",
            "\")\"",
            "\"=\"",
            "\"[\"",
            "\"]\"",
            "<token of kind 8>",
            "<token of kind 9>",
            "<token of kind 10>",
            "\"*\"",
            "\"-\"",
            "\".\"",
            "\",\"",
            "<DELIMITER>",
            "<NEWLINE>",
            "\".ends\"",
            "\".end\"",
            "<VALUE>",
            "<STRING>",
            "<EXPRESSION>",
            "<REFERENCE>",
            "<WORD>",
            "<IDENTIFIER>",
            "<DIGIT>",
            "<LETTER>",
            "<CHARACTER>",
            "<SPECIAL>"
        };
    }
}