using SpiceSharp.Simulations;
using System;
using System.Linq;

namespace SpiceSharp.Components.NoiseSources;

/// <summary>
/// A time-domain noise source with a <c>KF * |I|^AF / f^beta</c> power spectral density. It is a
/// noise current that is injected between two nodes.
/// </summary>
/// <remarks>
/// A 1/f^beta noise source has infinite power at DC, so it cannot be produced by reusing white
/// noise directly. Instead, it is generated from multiple sections of log-spaced poles.
/// </remarks>
/// <seealso cref="TimeNoiseCurrentSource"/>
public class TimeNoiseFlicker : TimeNoiseCurrentSource
{
    private readonly double[] _amplitudes;

    /// <summary>
    /// Gets the roll-off exponent of the density, <c>beta</c> in <c>1/f^beta</c>.
    /// </summary>
    /// <value>
    /// The roll-off exponent.
    /// </value>
    public double Exponent { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="TimeNoiseFlicker" /> class with the <c>1/f</c>
    /// density that the SPICE models ask for.
    /// </summary>
    /// <param name="name">The name of the noise source. It has to be unique within the circuit.</param>
    /// <param name="noise">The transient noise simulation state.</param>
    /// <param name="biasing">The biasing simulation state.</param>
    /// <param name="pos">The positive node.</param>
    /// <param name="neg">The negative node.</param>
    /// <exception cref="ArgumentNullException">Thrown if any of the arguments is <c>null</c>.</exception>
    public TimeNoiseFlicker(string name, ITimeNoiseSimulationState noise, IBiasingSimulationState biasing,
        IVariable<double> pos, IVariable<double> neg)
        : this(name, noise, biasing, pos, neg, 1.0)
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="TimeNoiseFlicker" /> class.
    /// </summary>
    /// <param name="name">The name of the noise source. It has to be unique within the circuit.</param>
    /// <param name="noise">The transient noise simulation state.</param>
    /// <param name="biasing">The biasing simulation state.</param>
    /// <param name="pos">The positive node.</param>
    /// <param name="neg">The negative node.</param>
    /// <param name="exponent">The roll-off exponent <c>beta</c> of <c>1/f^beta</c>. It has to lie
    /// strictly between <see cref="FlickerWeights.MinimumExponent"/> and
    /// <see cref="FlickerWeights.MaximumExponent"/>.</param>
    /// <exception cref="ArgumentNullException">Thrown if any of the arguments is <c>null</c>.</exception>
    /// <exception cref="ArgumentOutOfRangeException">Thrown if <paramref name="exponent"/> is out of
    /// range.</exception>
    public TimeNoiseFlicker(string name, ITimeNoiseSimulationState noise, IBiasingSimulationState biasing,
        IVariable<double> pos, IVariable<double> neg, double exponent)
        : this(name, noise.ThrowIfNull(nameof(noise)), biasing, pos, neg, noise.GetFlickerWeights(exponent))
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="TimeNoiseFlicker" /> class from weights that
    /// have already been resolved, which is what fixes the number of shaping sections.
    /// </summary>
    private TimeNoiseFlicker(string name, ITimeNoiseSimulationState noise, IBiasingSimulationState biasing,
        IVariable<double> pos, IVariable<double> neg, FlickerWeights weights)
        : base(name, noise, biasing, pos, neg, weights.Amplitudes.Count)
    {
        Exponent = weights.Exponent;

        // The weights are resolved once and held, rather than looked up per timepoint: they only
        // depend on the ladder and the exponent, both of which are fixed for the whole run.
        _amplitudes = weights.Amplitudes.ToArray();
    }

    /// <summary>
    /// Computes the flicker noise density coefficient. This is
    /// <c>coefficient * |current|^currentExponent</c>.
    /// </summary>
    /// <param name="coefficient">The flicker noise coefficient. For a SPICE model this is <c>KF</c>,
    /// divided by whatever geometry factor the model refers its noise to.</param>
    /// <param name="currentExponent">The exponent on the current, SPICE's <c>AF</c>.</param>
    /// <param name="current">The bias current that the noise is generated by.</param>
    /// <remarks>
    /// The coefficient is what <see cref="TimeNoiseSource.NoiseDensity"/> reports, so for a flicker
    /// source that property is the density at 1 Hz rather than a density that holds at every
    /// frequency.
    /// </remarks>
    public void Compute(double coefficient, double currentExponent, double current)
    {
        // The floor is the one the frequency-domain behaviors apply, and it is what makes the
        // amplitude vanish only when the coefficient does. The two common exponents are special-cased
        // because they cost nothing that way.
        double magnitude = Math.Max(Math.Abs(current), 1e-38);
        double power;
        if (currentExponent == 1.0)
            power = magnitude;
        else if (currentExponent == 2.0)
            power = magnitude * magnitude;
        else
            power = Math.Exp(currentExponent * Math.Log(magnitude));

        // Not through SetNoiseDensity: that one multiplies by the equivalent noise bandwidth of a
        // white source pushed through the band-limit shaper, and the power of a flicker source is
        // already fully determined by the coefficient and the weights of its ladder.
        NoiseDensity = coefficient * power;
        Amplitude = Math.Sqrt(NoiseDensity);
    }

    /// <inheritdoc/>
    /// <remarks>
    /// Walks the shared ladder instead of the single band-limit point. The amplitude of a section is
    /// the square root of its weight, and the density coefficient is applied once to the sum.
    /// </remarks>
    protected override double Shape(bool initialize)
    {
        double sum = 0.0;
        if (initialize)
        {
            // Every section starts from its own stationary distribution. Zero-initializing would bias
            // the first time constants of the slowest section low, over a stretch of the run that
            // can be most of it, and it would look like a settling transient rather than a bug.
            var stationary = TimeNoisePoint.Stationary(State.BandLimitOrder);
            for (int i = 0; i < _amplitudes.Length; i++)
                sum += _amplitudes[i] * Propagate(i, stationary);
            return sum;
        }

        // A model without a flicker coefficient has nothing to shape, and walking a ladder of a
        // dozen sections to multiply the result by zero would be most of what such a device pays per
        // timepoint. The amplitude only vanishes when the coefficient does, per Compute, so the
        // shaping state that stands still here belongs to a source that is silent for the whole run.
        if (Amplitude <= 0.0)
            return 0.0;

        var ladder = State.FlickerLadder;
        for (int i = 0; i < _amplitudes.Length; i++)
            sum += _amplitudes[i] * Propagate(i, ladder[i]);
        return sum;
    }
}
