name: Publish to NuGet

on:
  release:
    branches: [ master ]
    types: [ published ]
    tags:
      - 'generator-v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Setup dotnet tooling
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Compile Spice# generator
      run: dotnet build SpiceSharpGenerator\SpiceSharpGenerator.csproj --configuration Release --no-restore

    - name: Publish to NuGet
      env:
        APIKEY: ${{ secrets.NUGET_APIKEY }}
      run: dotnet nuget push ".\build\bin\SpiceSharpGenerator\SpiceSharpGenerator.*.nupkg" -k $env:APIKEY -s "https://api.nuget.org/v3/index.json"
      
